package com.baohao.departmentwebsite.model;

import java.util.Date;

public class ArticleList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.arti_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer artiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.arti_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String artiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.arti_author
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String artiAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.arti_id
     *
     * @return the value of article_list.arti_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getArtiId() {
        return artiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.arti_id
     *
     * @param artiId the value for article_list.arti_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setArtiId(Integer artiId) {
        this.artiId = artiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.arti_name
     *
     * @return the value of article_list.arti_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getArtiName() {
        return artiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.arti_name
     *
     * @param artiName the value for article_list.arti_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setArtiName(String artiName) {
        this.artiName = artiName == null ? null : artiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.arti_author
     *
     * @return the value of article_list.arti_author
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getArtiAuthor() {
        return artiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.arti_author
     *
     * @param artiAuthor the value for article_list.arti_author
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setArtiAuthor(String artiAuthor) {
        this.artiAuthor = artiAuthor == null ? null : artiAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.create_time
     *
     * @return the value of article_list.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.create_time
     *
     * @param createTime the value for article_list.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.update_time
     *
     * @return the value of article_list.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.update_time
     *
     * @param updateTime the value for article_list.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}