package com.baohao.departmentwebsite.model;

import java.util.Date;

public class ImageInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.img_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.img_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.img_group_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer imgGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.img_path
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.img_id
     *
     * @return the value of image_info.img_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.img_id
     *
     * @param imgId the value for image_info.img_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.img_name
     *
     * @return the value of image_info.img_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.img_name
     *
     * @param imgName the value for image_info.img_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.img_group_id
     *
     * @return the value of image_info.img_group_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getImgGroupId() {
        return imgGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.img_group_id
     *
     * @param imgGroupId the value for image_info.img_group_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setImgGroupId(Integer imgGroupId) {
        this.imgGroupId = imgGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.img_path
     *
     * @return the value of image_info.img_path
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.img_path
     *
     * @param imgPath the value for image_info.img_path
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.create_time
     *
     * @return the value of image_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.create_time
     *
     * @param createTime the value for image_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}