package com.baohao.departmentwebsite.model;

import java.util.Date;

public class ManagerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer magId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_email
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String magEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_pwd
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String magPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String magName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_image
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String magImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_login_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date magLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.mag_login_ip
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private String magLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_id
     *
     * @return the value of manager_info.mag_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getMagId() {
        return magId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_id
     *
     * @param magId the value for manager_info.mag_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagId(Integer magId) {
        this.magId = magId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_email
     *
     * @return the value of manager_info.mag_email
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getMagEmail() {
        return magEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_email
     *
     * @param magEmail the value for manager_info.mag_email
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagEmail(String magEmail) {
        this.magEmail = magEmail == null ? null : magEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_pwd
     *
     * @return the value of manager_info.mag_pwd
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getMagPwd() {
        return magPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_pwd
     *
     * @param magPwd the value for manager_info.mag_pwd
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagPwd(String magPwd) {
        this.magPwd = magPwd == null ? null : magPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_name
     *
     * @return the value of manager_info.mag_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getMagName() {
        return magName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_name
     *
     * @param magName the value for manager_info.mag_name
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagName(String magName) {
        this.magName = magName == null ? null : magName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_image
     *
     * @return the value of manager_info.mag_image
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getMagImage() {
        return magImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_image
     *
     * @param magImage the value for manager_info.mag_image
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagImage(String magImage) {
        this.magImage = magImage == null ? null : magImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_login_time
     *
     * @return the value of manager_info.mag_login_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getMagLoginTime() {
        return magLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_login_time
     *
     * @param magLoginTime the value for manager_info.mag_login_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagLoginTime(Date magLoginTime) {
        this.magLoginTime = magLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.mag_login_ip
     *
     * @return the value of manager_info.mag_login_ip
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public String getMagLoginIp() {
        return magLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.mag_login_ip
     *
     * @param magLoginIp the value for manager_info.mag_login_ip
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setMagLoginIp(String magLoginIp) {
        this.magLoginIp = magLoginIp == null ? null : magLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.create_time
     *
     * @return the value of manager_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.create_time
     *
     * @param createTime the value for manager_info.create_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.update_time
     *
     * @return the value of manager_info.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.update_time
     *
     * @param updateTime the value for manager_info.update_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}