package com.baohao.departmentwebsite.model;

import java.util.Date;

public class VisitInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.visit_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer visitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.visit_count
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Integer visitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_info.visit_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    private Date visitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.visit_id
     *
     * @return the value of visit_info.visit_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.visit_id
     *
     * @param visitId the value for visit_info.visit_id
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.visit_count
     *
     * @return the value of visit_info.visit_count
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.visit_count
     *
     * @param visitCount the value for visit_info.visit_count
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_info.visit_time
     *
     * @return the value of visit_info.visit_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_info.visit_time
     *
     * @param visitTime the value for visit_info.visit_time
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }
}