package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.ArticleList;
import com.baohao.departmentwebsite.model.ArticleListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    long countByExample(ArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByExample(ArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByPrimaryKey(Integer artiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insert(ArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insertSelective(ArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    List<ArticleList> selectByExample(ArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    ArticleList selectByPrimaryKey(Integer artiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleList record, @Param("example") ArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExample(@Param("record") ArticleList record, @Param("example") ArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKey(ArticleList record);
}