package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.FnInfo;
import com.baohao.departmentwebsite.model.FnInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    long countByExample(FnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int deleteByExample(FnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int deleteByPrimaryKey(Integer fnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int insert(FnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int insertSelective(FnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    List<FnInfo> selectByExample(FnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    FnInfo selectByPrimaryKey(Integer fnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") FnInfo record, @Param("example") FnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByExample(@Param("record") FnInfo record, @Param("example") FnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByPrimaryKeySelective(FnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fn_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByPrimaryKey(FnInfo record);
}