package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.ManagerInfo;
import com.baohao.departmentwebsite.model.ManagerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    long countByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int deleteByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int deleteByPrimaryKey(Integer magId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int insert(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int insertSelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    List<ManagerInfo> selectByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    ManagerInfo selectByPrimaryKey(Integer magId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByExample(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByPrimaryKeySelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sun Apr 22 22:44:34 CST 2018
     */
    int updateByPrimaryKey(ManagerInfo record);
}