package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.VideoGroupInfo;
import com.baohao.departmentwebsite.model.VideoGroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    long countByExample(VideoGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int deleteByExample(VideoGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int insert(VideoGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int insertSelective(VideoGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    List<VideoGroupInfo> selectByExample(VideoGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    VideoGroupInfo selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoGroupInfo record, @Param("example") VideoGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoGroupInfo record, @Param("example") VideoGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VideoGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoGroupInfo record);
}