package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.VideoInfo;
import com.baohao.departmentwebsite.model.VideoInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    long countByExample(VideoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByExample(VideoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insert(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insertSelective(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    List<VideoInfo> selectByExample(VideoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    VideoInfo selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") VideoInfo record, @Param("example") VideoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExample(@Param("record") VideoInfo record, @Param("example") VideoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKeySelective(VideoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKey(VideoInfo record);
}