package com.baohao.departmentwebsite.dao;

import com.baohao.departmentwebsite.model.VisitInfo;
import com.baohao.departmentwebsite.model.VisitInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    long countByExample(VisitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByExample(VisitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int deleteByPrimaryKey(Integer visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insert(VisitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int insertSelective(VisitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    List<VisitInfo> selectByExample(VisitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    VisitInfo selectByPrimaryKey(Integer visitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") VisitInfo record, @Param("example") VisitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByExample(@Param("record") VisitInfo record, @Param("example") VisitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKeySelective(VisitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_info
     *
     * @mbg.generated Mon Apr 23 08:28:50 CST 2018
     */
    int updateByPrimaryKey(VisitInfo record);
}